apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: skills-cluster
  version: "1.29"
  region: ap-northeast-2

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

vpc:
  subnets:
    public:
      ap-northeast-2a: { id: public_a }
      ap-northeast-2b: { id: public_b }
      ap-northeast-2c: { id: public_c }
    private:
      ap-northeast-2a: { id: private_a }
      ap-northeast-2b: { id: private_b }
      ap-northeast-2c: { id: private_c }

managedNodeGroups:
  - name: skills-node
    labels: { app: skills }
    instanceName: skills-node
    instanceType: c5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 20
    privateNetworking: true
    # ssh:
    #   allow: true
    #   publicKeyName: <KeyPair>
