apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: skills
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 362708816803.dkr.ecr.ap-northeast-2.amazonaws.com/api:latest
          ports:
            - containerPort: 8080
